using DelimitedFiles
# This script loads the intermediate input objects generated by the original
# R/Rcpp replication package for the All-votes dataset.
#
# It does not read the raw UN voting data directly. Instead, it starts from
# the processed matrices, vectors, starting values, and indexing structures
# saved by the original R code in the Output/ folder.

const DATA_PATH = joinpath(@__DIR__, "..", "data")

function load_data_file(filename)
    return readdlm(joinpath(DATA_PATH, filename))
end

# Country-session by observation index matrix.
# Used to map country-session ideal points to observation-level vote data.

IObsMat = load_data_file("IObsMat_All_Apr2020.txt")

# Number of observed votes for each country-session.

IndN = vec(load_data_file("IndN_All_Apr2020.txt"))
IndN = Int.(IndN)

# Initial parameter values loaded from the original R replication package.
# These objects are used to initialize the Julia MCMC estimation procedure.

BetaVector = vec(load_data_file("BetaVectorSaveRW_All_Apr2020.txt"))

Z = vec(load_data_file("ZSaveRW_All_Apr2020.txt"))

SmoothVector = vec(load_data_file("SmoothVector_All_Apr2020.txt"))

# Country and UN General Assembly session identifiers
# associated with each country-session observation.

CountryList = vec(load_data_file("CountryList_All_Apr2020.txt"))

SessionList = vec(load_data_file("SessionList_All_Apr2020.txt"))

# GapYear identifies breaks in the country-session time series.
# TRUE indicates a temporal gap between consecutive observations.
# Convert string values from the original R output into Julia Bool values.

GapYear = vec(load_data_file("GapYear_All_Apr2020.txt"))
GapYear = GapYear .== "TRUE"

# Vote-level threshold parameters.

Gamma1 = vec(load_data_file("Gamma1RW_All_Apr2020.txt"))

Gamma2 = vec(load_data_file("Gamma2RW_All_Apr2020.txt"))

# Vote-level indexing: number of observations per vote and start/end rows

VoteN = vec(load_data_file("VoteN_All_Apr2020.txt"))
VoteN = Int.(VoteN)

VoteStartEnd = load_data_file("VoteStartEnd_All_Apr2020.txt")
VoteStartEnd = Int.(VoteStartEnd)

# Observed vote categories.
# Column 6 of AllData contains the observed vote code used by the sampler.

AllData = load_data_file("AllData_All_Apr2020.txt")
yObs = Int.(AllData[:, 6])

println("Loaded All inputs")
println(length(Gamma1))
println(length(Gamma2))
println(length(VoteN))
println(size(VoteStartEnd))
println(length(yObs))