using DelimitedFiles

# This script loads the intermediate input objects generated by the original
# R/Rcpp replication package for the Important-votes dataset.
#
# The script does not read raw UN voting records directly. Instead, it loads
# the processed matrices, vectors, indexing structures, and initial parameter
# values used by the Bayesian estimation procedure.

const DATA_PATH = joinpath(@__DIR__, "..", "data")

# a function for loading processed replication files.
function load_data_file(filename)
    return readdlm(joinpath(DATA_PATH, filename))
end

# Country-session by observation index matrix.
# Used to map observations to country-session ideal points.
IObsMat = load_data_file("IObsMat_Important_Apr2020.txt")

# Number of observed votes for each country-session.
IndN = vec(load_data_file("IndN_Important_Apr2020.txt"))
IndN = Int.(IndN)

# Initial parameter values loaded from the original R replication package.
# These objects are used to initialize the Julia MCMC estimation procedure.
BetaVector = vec(load_data_file("BetaVectorSaveRW_Important_Apr2020.txt"))

Z = vec(load_data_file("ZSaveRW_Important_Apr2020.txt"))

# Smoothing structure used in the dynamic prior specification.
SmoothVector = vec(load_data_file("SmoothVector_Important_Apr2020.txt"))

# Country and UNGA session identifiers used to index
# each country-session ideal point.
CountryList = vec(load_data_file("CountryList_Important_Apr2020.txt"))

SessionList = vec(load_data_file("SessionList_Important_Apr2020.txt"))

# GapYear identifies breaks in the country-session time series.
# TRUE indicates a temporal gap between consecutive observations.
# Convert string values from the original R output into Julia Bool values.
GapYear = vec(load_data_file("GapYear_Important_Apr2020.txt"))
GapYear = GapYear .== "TRUE"

# Vote-level threshold parameters used in the ordinal voting model.
Gamma1 = vec(load_data_file("Gamma1RW_Important_Apr2020.txt"))

Gamma2 = vec(load_data_file("Gamma2RW_Important_Apr2020.txt"))

# Vote-level indexing structures.
VoteN = vec(load_data_file("VoteN_Important_Apr2020.txt"))
VoteN = Int.(VoteN)

VoteStartEnd = load_data_file("VoteStartEnd_Important_Apr2020.txt")
VoteStartEnd = Int.(VoteStartEnd)

# Observed vote outcomes.
# Column 6 contains the observed vote category used by the sampler.
AllData = load_data_file("AllData_Important_Apr2020.txt")
yObs = Int.(AllData[:, 6])

println("Loaded gamma inputs")

println(length(Gamma1))
println(length(Gamma2))
println(length(VoteN))
println(size(VoteStartEnd))
println(length(yObs))