using DelimitedFiles
# This script loads the intermediate input objects generated by the original
# R/Rcpp replication package for the All-votes dataset.
#
# It does not read the raw UN voting data directly. Instead, it starts from
# the processed matrices, vectors, starting values, and indexing structures
# saved by the original R code in the Output/ folder.

const R_OUTPUT_PATH = raw"C:\Users\HP 14-DW1012NL\Desktop\COMPUTATIONAL\United-Nations-General-Assembly-Votes-and-Ideal-Points-master\United-Nations-General-Assembly-Votes-and-Ideal-Points-master\Output"

function load_r_output(filename)
    return readdlm(joinpath(R_OUTPUT_PATH, filename))
end

# Country-session by observation index matrix.
# Used to map country-session ideal points to observation-level vote data.

IObsMat = load_r_output("IObsMat_All_Apr2020.txt")

# Number of observed votes for each country-session.

IndN = vec(load_r_output("IndN_All_Apr2020.txt"))
IndN = Int.(IndN)

# Initial parameter values loaded from the original R replication package.
# These objects are used to initialize the Julia MCMC estimation procedure.

BetaVector = vec(load_r_output("BetaVectorSaveRW_All_Apr2020.txt"))

Z = vec(load_r_output("ZSaveRW_All_Apr2020.txt"))

SmoothVector = vec(load_r_output("SmoothVector_All_Apr2020.txt"))

# Country and session identifiers used for the dynamic prior.

CountryList = vec(load_r_output("CountryList_All_Apr2020.txt"))

SessionList = vec(load_r_output("SessionList_All_Apr2020.txt"))

# GapYear identifies breaks in the country-session time series.
# TRUE indicates a temporal gap between consecutive observations.
# Convert string values from the original R output into Julia Bool values.

GapYear = vec(load_r_output("GapYear_All_Apr2020.txt"))
GapYear = GapYear .== "TRUE"

# Vote-level threshold parameters.

Gamma1 = vec(load_r_output("Gamma1RW_All_Apr2020.txt"))

Gamma2 = vec(load_r_output("Gamma2RW_All_Apr2020.txt"))

# Vote-level indexing: number of observations per vote and start/end rows

VoteN = vec(load_r_output("VoteN_All_Apr2020.txt"))
VoteN = Int.(VoteN)

VoteStartEnd = load_r_output("VoteStartEnd_All_Apr2020.txt")
VoteStartEnd = Int.(VoteStartEnd)

# Observed vote categories.
# Column 6 of AllData contains the observed vote code used by the sampler.

AllData = load_r_output("AllData_All_Apr2020.txt")
yObs = Int.(AllData[:, 6])

println("Loaded All inputs")
println(length(Gamma1))
println(length(Gamma2))
println(length(VoteN))
println(size(VoteStartEnd))
println(length(yObs))