# Master replication function for the UN ideal point estimator.
#
# This function runs the Bayesian MCMC estimation procedure and can be used
# either as:
#
#   - a lightweight smoke test;
#   - the full MCMC replication;
#
# on either:
#
#   - the All-votes dataset;
#   - the Important-votes dataset.
#
# The sampler iteratively updates:
#
#   1. theta ideal points
#   2. gamma threshold parameters
#   3. latent Z utilities
#   4. beta discrimination parameters
#
# The function stores posterior draws after burn-in and thinning, and computes
# posterior mean ideal point estimates at the end of the run.
#
# Usage examples:
#
#   run_replication()
#
#       Default behavior:
#       - dataset = :all
#       - test = true
#
#       Runs a lightweight smoke test on the All-votes dataset.
#
#
#   run_replication(test = false)
#
#       Runs the full MCMC replication on the All-votes dataset.
#
#
#   run_replication(dataset = :important)
#
#       Runs the smoke test on the Important-votes dataset.
#
#
#   run_replication(dataset = :important, test = false)
#
#       Runs the full MCMC replication on the Important-votes dataset.
#
#
# Arguments:
#
#   dataset
#
#       Selects the dataset used for estimation.
#
#       Possible values:
#
#           :all
#           :important
#
#
#   test
#
#       Selects whether the function runs:
#
#           - a lightweight smoke test (true)
#           - the full replication MCMC (false)
#
#
# The smoke test uses fewer MCMC iterations and is intended only for
# diagnostic and reproducibility verification.
#
# The full run reproduces the final estimation outputs reported in the
# replication report and associated figures.

using Statistics
using DelimitedFiles


function run_replication(; dataset = :all, test = true)
    

    # Validate dataset selection.
    if !(dataset in (:all, :important))
        error("dataset must be either :all or :important")
    end

    println("Running UN ideal point replication")
    println("Dataset: ", dataset)
    println("Test mode: ", test)

    # Repository-relative paths for processed inputs and generated outputs.
    DATA_PATH = joinpath(@__DIR__, "..", "data")
    OUTPUT_PATH = joinpath(@__DIR__, "..", "output")
    mkpath(OUTPUT_PATH)

    # Select filename suffix corresponding to the chosen dataset.
    suffix = dataset == :all ? "All_Apr2020" : "Important_Apr2020"

    # Helper function for loading processed replication inputs.
    function load_data_file(name)
        return readdlm(joinpath(DATA_PATH, name))
    end

    # Load the country-session by observation index matrix.
    # This matrix maps each country-session ideal point to the vote-level
    # observations in which it appears.
    IObsMat = load_data_file("IObsMat_$(suffix).txt")

    # Number of observed votes associated with each country-session.
    # These values are used together with IObsMat to construct observation-level
    # theta vectors.
    IndN = vec(load_data_file("IndN_$(suffix).txt"))
    IndN = Int.(IndN)

    # Initial beta discrimination parameters and latent Z utilities.
    # These are processed objects generated by the original R/Rcpp package and
    # are used as starting values for the Julia sampler.
    BetaVector = vec(load_data_file("BetaVectorSaveRW_$(suffix).txt"))
    Z = vec(load_data_file("ZSaveRW_$(suffix).txt"))

    # Smoothing vector used in the dynamic prior for country-session ideal points.
    SmoothVector = vec(load_data_file("SmoothVector_$(suffix).txt"))

    # Country and UN General Assembly session identifiers.
    # These identify the country-session panel structure used by the dynamic
    # ideal point model.
    CountryList = vec(load_data_file("CountryList_$(suffix).txt"))
    SessionList = vec(load_data_file("SessionList_$(suffix).txt"))

    # Indicator for gaps in the country-session time series.
    # The original R output stores these as strings; here they are converted
    # into Julia Bool values.
    GapYear = vec(load_data_file("GapYear_$(suffix).txt"))
    GapYear = GapYear .== "TRUE"

    # Vote-level threshold parameters for the ordinal voting model.
    # These determine the cutpoints between voting categories.
    Gamma1 = vec(load_data_file("Gamma1RW_$(suffix).txt"))
    Gamma2 = vec(load_data_file("Gamma2RW_$(suffix).txt"))

    # Vote-level indexing structures.
    # VoteN stores the number of observations for each roll-call vote.
    # VoteStartEnd stores the start and end rows for each vote.
    VoteN = vec(load_data_file("VoteN_$(suffix).txt"))
    VoteN = Int.(VoteN)

    VoteStartEnd = load_data_file("VoteStartEnd_$(suffix).txt")
    VoteStartEnd = Int.(VoteStartEnd)

    # Observed vote outcomes.
    # Column 6 of AllData contains the vote category used by the sampler.
    AllData = load_data_file("AllData_$(suffix).txt")
    yObs = Int.(AllData[:, 6])
   

    # MCMC hyperparameters and prior settings.
    Smooth = 0.5
    sigmaMH = 0.1

    BetaPrior = 0.0
    S2BetaPrior = 1.0

    # Select MCMC length depending on whether the function is run
    # in smoke-test mode or full-replication mode.
    if test
        K = 500
        Burn = 100
        Thin = 10
    else
        K = 20000
        Burn = 4000
        Thin = 50
    end

    # Print selected MCMC configuration.
    println("MCMC settings:")
    println("K = ", K)
    println("Burn = ", Burn)
    println("Thin = ", Thin)

    # Initialize theta values and posterior storage objects.
    Theta = zeros(length(IndN))

    SavedDraws = Int((K - Burn) / Thin)
    ThetaStore = zeros(SavedDraws, length(Theta))

    save_index = 0

    # Main Gibbs / Metropolis-Hastings MCMC loop.
    for iter in 1:K

        println("Iteration: ", iter)

        # Expand country-session theta values to the observation level.
        ThetaVector = populate_theta_vector(
            IObsMat,
            Theta,
            IndN,
            length(BetaVector)
        )

        # Build dynamic lagged theta prior across UNGA sessions.
        LagThetaPrior = build_lag_prior(
            Theta,
            CountryList,
            SessionList,
            GapYear
        )

        # Compute posterior theta moments conditional on current parameters.
        ThetaMean, VarTheta = compute_theta_mean_var(
            IObsMat,
            IndN,
            BetaVector,
            Z,
            LagThetaPrior,
            SmoothVector,
            Smooth
        )

        # Draw theta values from the conditional Gaussian posterior.
        Theta =
            ThetaMean .+
            sqrt.(VarTheta) .* randn(length(ThetaMean))

        # Apply truncation and normalization used in the original estimator.
        Theta = clamp.(Theta, -5, 5)
        Theta = (Theta .- mean(Theta)) ./ std(Theta)

        # Rebuild observation-level theta vector after updating theta.
        ThetaVector = populate_theta_vector(
            IObsMat,
            Theta,
            IndN,
            length(BetaVector)
        )

        # Expand vote-level thresholds to observation-level vectors.
        Gamma1Vector = r_rep(Gamma1, VoteN)
        Gamma2Vector = r_rep(Gamma2, VoteN)

        # Construct lower and upper truncation bounds for latent utilities.
        gLo =
            -99 .* (yObs .== 1) .+
            Gamma1Vector .* (yObs .== 2) .+
            Gamma2Vector .* (yObs .== 3)

        gHi =
            Gamma1Vector .* (yObs .== 1) .+
            Gamma2Vector .* (yObs .== 2) .+
            99 .* (yObs .== 3)

        # Metropolis-Hastings update for gamma threshold parameters.
        Gamma1, Gamma2, gLo, gHi, AcceptTemp =
            update_gamma(
                Gamma1,
                Gamma2,
                BetaVector,
                ThetaVector,
                yObs,
                VoteN,
                VoteStartEnd,
                gLo,
                gHi,
                sigmaMH
            )

        # Update latent continuous utilities.
        Z = update_z(
            BetaVector,
            ThetaVector,
            gLo,
            gHi,
            length(yObs)
        )

        # Update beta discrimination parameters.
        Beta, BetaVector, BetaMean, VarBeta =
            update_beta(
                ThetaVector,
                Z,
                VoteStartEnd,
                VoteN,
                BetaPrior,
                S2BetaPrior
            )

        # Print simple diagnostics for monitoring chain behavior.
        println("Theta mean: ", mean(Theta))
        println("Beta mean: ", mean(Beta))
        println("Gamma acceptance: ", mean(AcceptTemp))

        # Store posterior draws after burn-in and according to thinning interval.
        if iter > Burn && ((iter - Burn) % Thin == 0)
            save_index += 1
            ThetaStore[save_index, :] = Theta
            println("Saved draw: ", save_index)
        end
    end

    # Compute posterior mean ideal point estimates.
    ThetaEst = vec(mean(ThetaStore, dims = 1))

    # Select output filename based on dataset and test/full mode.
    output_name =
        if test
            dataset == :all ? "ThetaEst_smoke_test_all.csv" : "ThetaEst_smoke_test_important.csv"
        else
            dataset == :all ? "ThetaEst_full_all.csv" : "ThetaEst_full.csv"
        end

    output_file = joinpath(OUTPUT_PATH, output_name)

    # Save posterior mean ideal point estimates to output/.
    writedlm(output_file, ThetaEst, ",")

    println("Theta estimates computed")
    println("Saved output:")
    println(output_file)

    return output_file
end